#!/usr/bin/env bash

if [[ -z "${GH_REPO}" ]]; then
  echo "No github repo provided. Nothing to clone."
else
  echo "Found github repo. Checking for a github personal access token."
  if [[ -z "${GH_TOKEN}" ]]; then
    echo "No github token provided. Cloning public repo."
    sudo git clone $GH_REPO
  else
    echo "found a github token. Cloning repo."
    sudo git clone $GH_TOKEN@$GH_REPO
  fi
fi

export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

cp /tmp/.bashrc /home/coder/.bashrc
ls -ltra /home/coder

exec /usr/lib/code-server/bin/code-server "$@"
